### ISSUE TITLE
Deployments

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/Azure-RMSDocs#1002]
Hello,
We have deployed 3rd update of this new UL client, still we see some issues for random users, would be good to add "Troubleshooting" section for Administrators in this documentation for new UL client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a890ae-43df-fa2d-add9-3b2314be89e5
* Version Independent ID: e4cd0cae-dce4-627c-398b-6fa2e22b17c6
* Content: [Azure Information Protection unified labeling client admin guide](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@lightupdifire  Sorry to hear you're having problems with the unified labeling client. As with all the documentation on this site for Azure Information Protection, we document "by design" and resources for support and troubleshooting (https://docs.microsoft.com/en-us/azure/information-protection/information-support#support-options-and-community-resources). To help admins find this link for the unified labeling client, I've now added it to the admin guide, here: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide#installation-checks-and-troubleshooting 

If you have feedback about this client, I encourage you to share it with the Azure Information Protection team on their Yammer site: https://www.yammer.com/AskIPTeam

**Comment by cabailey** [comment]
#please-close
