### ISSUE TITLE
Problem with Step 4

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Azure-RMSDocs#1034]
I'm in a new demo tenant, when I get to  Step 4 above in the Edit the Policy section,  I don't have any labels to choose as a Default Label. It seems like a step to create a label may be missing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c05358db-2c5f-fd01-1077-4255f06352be
* Version Independent ID: fa8b14ad-4aa1-c34c-9103-e3f048ee8828
* Content: [Tutorial - Edit the Azure Information Protection policy - AIP](https://docs.microsoft.com/en-us/azure/information-protection/infoprotect-quick-start-tutorial)
* Content Source: [Azure-RMSDocs/infoprotect-quick-start-tutorial.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/infoprotect-quick-start-tutorial.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@DeanGross  Thanks for flagging this, Dean. Yes, I missed this potential gap when they stopped creating & publishing labels automatically for new tenants.  The prereqs for this tutorial included adding Azure Information Protection to the Azure portal and activating protecting, but didn't include adding labels to the global policy, which also publishes them from Azure.  I've now added this and also updated the related quickstart so that labels are always added to the global policy (not optional, as before). 

Having documentation that covers all variations is really tricky while we're in this transition stage - for example, tenants could have labels created & published from Azure automatically, tenants could have labels created but published only from the Office/M365 admin centers, tenants might not yet be on the unified labeling platform ….  I didn't really want to put creating & publishing labels into each of the tutorials for the classic client when we could cover this once in a quickstart.  But the downside of adding this to the quickstart is you don't need to publish labels from Azure if you're not using the classic client.  Asking people to choose their client before they do the quickstart feels too high an entry barrier.  What do you think?  Do the updates I just published fix this issue or are further updates needed - such as different quickstarts for each client?

**Comment by DeanGross** [comment]
Thanks, as usual, you have provide an excellent answer. After attempting this, I went back to some of the other instructions and performed the label creation step which provided the missing items so that this Tutorial could be completed. 
Your updates should help other prevent other people from running into the issue I had.

**Comment by cabailey** [comment]
Thanks for the update!
#please-close
