### ISSUE TITLE
need more FAQ on MAC suport

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/Azure-RMSDocs#1038]
need more FAQ on MAC support with the native office client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1cb834-9023-f79b-115e-199c4e1af17b
* Version Independent ID: a0ea852a-eedd-b205-91c0-bfa8732fa9f3
* Content: [FAQs for classification & labeling - AIP](https://docs.microsoft.com/en-us/azure/information-protection/faqs-infoprotect)
* Content Source: [Azure-RMSDocs/faqs-infoprotect.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/faqs-infoprotect.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
When you're using the built-in labeling client in Office rather than one of the Azure Information Protection clients, use the Office documentation - for example, https://support.office.com/en-us/article/Apply-sensitivity-labels-to-your-documents-and-email-within-Office-2f96e7cd-d5a4-403b-8bd7-4cc636bae0f9#ID0EBFAAA=Office_365_for_Mac

**Comment by cabailey** [comment]
To help other people find the relevant information, I added the following FAQ: https://docs.microsoft.com/en-us/azure/information-protection/faqs-infoprotect#where-can-i-find-information-about-using-sensitivity-labels-in-office

**Comment by cabailey** [comment]
#please-close
