### ISSUE TITLE
Sensitive Labels are to be support

### ISSUE THREAD

**Issue by erroltuparker** [MicrosoftDocs/Azure-RMSDocs#1041]
This article doesn't reflect that applying sensitive labels aren't supported til Office 365 1910+.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80433bf5-fdf0-92a2-6b0d-b559511d6ce6
* Version Independent ID: 99d5c616-c99a-dbcd-4ef9-67fcf77c5133
* Content: [Configuration for clients to use Office apps with Azure RMS from AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-office-apps#feedback)
* Content Source: [Azure-RMSDocs/configure-office-apps.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-office-apps.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@erroltuparker This article is for using information rights management (IRM) features and not the sensitivity features that use built-in labeling. They are different features.  We'll look at making the distinctions clearer throughout the documentation because IRM support will continue for the other versions of Office apps.

**Comment by cabailey** [comment]
@erroltuparker You'll now find more information about the Office built-in labeling capabilities for sensitivity labels in this section: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#choose-which-labeling-client-to-use-for-windows-computers 

This issue seems to be addressed, so I'll ask for it to be closed.

#please-close
