### ISSUE TITLE
SCP Definition

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Azure-RMSDocs#1077]
What does SCP mean? Please add a definition,  its not specified anywhere on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ab1a060-e9b5-efe2-dae0-c181f275e635
* Version Independent ID: 59f861f4-5103-523a-045d-fb1d15a3d3cd
* Content: [Migrate AD RMS-Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-to-azure-rms?source=docs)
* Content Source: [Azure-RMSDocs/migrate-from-ad-rms-to-azure-rms.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/migrate-from-ad-rms-to-azure-rms.md)
* Service: **information-protection**
* Sub-service: **migration**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@DeanGross SCP = service connection point. For AD RMS, it's one of those abbreviations that people know better than the full name, which is included in the referenced link.  I excluded the full name here originally because I thought AD RMS customers would know it and as a quick summary, using the abbreviation would be easier to read.  However, after your feedback, I'll add the full name, here.

**Comment by cabailey** [comment]
Live now
#please-close
