### ISSUE TITLE
Office 365 ProPlus apps with built-in labeling

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/Azure-RMSDocs#1112]
Are there any additional instructions or notes that can be added here? How long does it typically take for changes to show up? Is there any way we can force a refresh for Office 365 ProPlus apps with built-in labeling? Seems to take days for the new or updated labels to appear. 

As an example, I have a secondary Outlook profile where sensitivity labels and the sensitivity tab do not appear in the Outlook client, but for this account, those labels appear in Outlook mobile and OWA. It would be great if there was a way to force the refresh for cases like this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2af8c9c8-cf06-49a4-5f22-bba526bc2734
* Version Independent ID: 868c2079-00f4-eae3-822f-49ae6c8ef63c
* Content: [Refresh Azure RMS templates - AIP](https://docs.microsoft.com/en-us/azure/information-protection/refresh-templates#feedback)
* Content Source: [Azure-RMSDocs/refresh-templates.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/refresh-templates.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by cabailey** [comment]
@terrogin  You are asking in the wrong place because this page is for protection template refresh, not labels.  If you have the Azure Information Protection unified labeling client, we've documented here https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#detailed-comparisons-for-the-azure-information-protection-clients that the policy (which contains the labels) is updated when an Office app opens and every 4 hours.  

For built-in labeling, the time varies but the documentation (https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels#publish-sensitivity-labels-by-creating-a-label-policy) states "Typically, users see the labels in their Office apps within a couple of hours. However, allow up to 24 hours for your label policies and any changes to them to replicate to all users and services."  If it's taking longer than that, contact Support (https://docs.microsoft.com/office365/admin/contact-support-for-business-products).

For feedback to the product team about built-in labeling, go to the UserVoice site for Office 365 Security & Compliance (https://office365.uservoice.com/forums/289138-office-365-security-compliance) and post it in the recently created Information Protection category. A shortcut to this site is to use the "This product" button in the Feedback section on any page in the M365 Compliance documentation. The same button in the Azure Information Protection documentation goes to the UserVoice site for Azure Information Protection where the engineering team owns the Azure Information Protection unified labeling client, but not the Office built-in labeling client.

**Comment by mlottner** [comment]
@terrogin Thanks again for taking the time to reach out to us on MSDocs. 
I'm closing this docs issue as I believe @cabailey answered your questions and directed you to the related UserVoice site to [leave feedback for the product team](https://office365.uservoice.com/forums/289138-office-365-security-compliance). Even with the issue closed, feel free to comment here if/as needed if you need additional help.

**Comment by mlottner** [comment]
#please-close
