### ISSUE TITLE
Question: can you later on move to a different LAWS?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/Azure-RMSDocs#1118]
To configure Label Analytics and Reporting you create a Log Analytics Workspace.  This can be moved between tenants and resource groups, given it remains in the same region, if I understood it correctly. But can you change AIP to log to a different LAWS then the one initially configured?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b75d85e-3cea-279c-feaf-c8f828f3d201
* Version Independent ID: 97d9a1b1-4db3-a1c0-69fe-8032ce615fc7
* Content: [Central reporting for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/reports-aip#configure-a-log-analytics-workspace-for-the-reports)
* Content Source: [Azure-RMSDocs/reports-aip.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/reports-aip.md)
* Service: **information-protection**
* Sub-service: **analytics**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by mlottner** [comment]
@andrePKI Thanks for taking the time to comment on docs!
Yes, AIP can be changed to log to a different LAWS instead of the LAWS originally configured -but it is a forward action only. Meaning all logs until the point of change will remain at the original LAWS. 
Closing this issue for now, but feel free to continue to comment here if/as needed. #please-close
