### ISSUE TITLE
AiP client and publish labels

### ISSUE THREAD

**Issue by karimzaki** [MicrosoftDocs/Azure-RMSDocs#1143]
Publishing labels or copy policies what are differences also after publishing or copy labels shall i use unified aip client or classic or both works

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b8e206-aa49-f558-09d4-506f5c725337
* Version Independent ID: 5169a618-9dea-3349-c365-0b16b57560c6
* Content: [Migrate Azure Information Protection labels to unified sensitivity labels - AIP](https://docs.microsoft.com/en-gb/azure/information-protection/configure-policy-migrate-labels#feedback)
* Content Source: [Azure-RMSDocs/configure-policy-migrate-labels.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-migrate-labels.md)
* Service: **information-protection**
* Sub-service: **labelmigrate**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@karimzaki Thanks for taking the time to give us documentation feedback. 
Are you asking which client you should choose to use? Or if you should publish or copy labels? Not sure I understand the documentation question you are asking. Can you clarify?  
Make sure you check out the very active Azure Information Protection product yammer group for any product questions and queries. This forum is for documentation questions and feedback only.

**Comment by karimzaki** [comment]
ok documentation feed back is when to use copy and when to use publish then after migration shall use classic AIP or AIP unified client

**Comment by cabailey** [comment]
@karimzaki  When to use copy policies and when to publish is documented on this page:

Use copy policies if you want a one-time copy of your policies with their policy settings and any advanced client settings to be sent to the admin center where you manage your labels: Office 365 Security & Compliance Center, Microsoft 365 security center, Microsoft 365 compliance center.

Successfully copied policies with their settings and labels are then automatically published to the users and groups that were assigned to the policies in the Azure portal.

Use Publish if you continue to use the classic client and you edit the labels outside the Azure portal.

After migration, you can use either client, even both on the same network if necessary. Use the following documentation to help you decide which client to use immediately after your label migration: https://docs.microsoft.com/en-gb/azure/information-protection/rms-client/use-client#choose-which-labeling-client-to-use-for-windows-computers  However, because the classic client is being deprecated, if you continue to use this client, you should plan to move off it in the near future.

**Comment by mlottner** [comment]
@karimzaki Thanks again for taking the time to leave us your question on MSDocs. 
I'm closing this issue as there is no related docs change to make, but feel free to continue to comment here if/as needed. 
#please-close
