### ISSUE TITLE
Is the AIP SDK available/functioning for GCC-High tenants?

### ISSUE THREAD

**Issue by jordonthreadgill** [MicrosoftDocs/Azure-RMSDocs#1272]
Hello,
I have a customer that is interested in building out the AIP SDK to protect their non-standard file types.  They would like to know if this feature and capability works in a GCC-High tenants?  There is no documentation supporting that it does work, but with that said, there is no documentation saying it won't work either.

Thanks,
Jordon

**Comment by batamig** [comment]
Hi @jordonthreadgill , thanks for sharing your docs question.
I'm tagging the content creators who can help here - @tommoser or @msmbaldwin can you take a look at this?

**Comment by tommoser** [comment]
We haven't published any docs around this, primarily due to nobody asking, yet :) Yes, GCC High is supported.

You'll need to have some mechanism to understand that the customer tenant is in GCC. For example, you might make a call to Graph and have the user log in. Once logged in, you can use the info from AAD to know that they're in GCC High. In MIP SDK, you'll need to set the cloud endpoint as part of the engine settings. In File SDK, that would look like:

```csharp
var engineSettings = new FileEngineSettings(identity.Email, authDelegate, "", "en-US")
{
      Cloud = Cloud.US_GCC_High                
};
```

And this will force the SDK to use GCC High for policy and protection services. Unfortunately, we don't have any method of auto discovery. We'll work to make the docs a bit clearer on this. 

https://docs.microsoft.com/en-us/information-protection/develop/concept-service-discovery#service-discovery-with-mipcloud

**Comment by jordonthreadgill** [comment]
Thank you for responding and also providing that extra information to get us started - I appreciate it.

I believe that because of the recent increase in security requirements for government contractors to meet various compliance controls there will be an upcoming increase in demand for AIP/MIP documentation.  Any additional documents that can be published supporting the limitations/differences of AIP/MIP/RMS in all of the Microsoft cloud spaces would be supremely helpful.

**Comment by tommoser** [comment]
Thanks for the heads up! I'll work to get the GCC specific details prioritized.

**Comment by batamig** [comment]
Hi @jordonthreadgill - thanks again for taking the time to send us your question!

I see that @tommoser 's already replied, so I'm going to close this. Feel free to continue to comment here as needed.

#please-close
