### ISSUE TITLE
DecryptAttachmentForEncryptOnly $true is not working, been set for 2 years

### ISSUE THREAD

**Issue by ckulick** [MicrosoftDocs/Azure-RMSDocs#1292]
Set-IRMConfiguration - DecryptAttachmentForEncryptOnly $true is enabled on our tenant for over 2 years.  Recently, this stopped working.  What changed that is making the attachment retain encryption?

**Comment by batamig** [comment]
Hi @ckulick,
Thanks for sending your question! These github questions go directly to the docs team.
Is there a specific docs clarification or fix that you're looking for? 

Otherwise, please open a support case, or you can also check our Yammer group at https://www.yammer.com/askipteam/#/home. 

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
