### ISSUE TITLE
Update Apple product names

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/Azure-RMSDocs#1371]
Where possible update references to "iOS" to reflect Apple current product names such as iPadOS, iOS where applicable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13769f09-0e43-6597-be6d-abe0bfc8caa7
* Version Independent ID: eb1e4a9d-a262-a614-39e7-feba86d83151
* Content: [Protected PDF viewers for Microsoft Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/protected-pdf-readers)
* Content Source: [Azure-RMSDocs/rms-client/protected-pdf-readers.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/protected-pdf-readers.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @adrianwells  - thanks for getting in touch!

I'm going to check back with the team about these changes before we make the updates and then will clarify as needed. 
I'm closing this issue for now since it's logged in our backlog, but feel free to continue to comment if you have more feedback.

We appreciate your contribution to docs!

#please-close
