### ISSUE TITLE
Azure Information Protection licensing datasheet is totally outdated: 2018

### ISSUE THREAD

**Issue by rtrigueiro** [MicrosoftDocs/Azure-RMSDocs#1386]
Hi Team,

This page needs review, at least on this point: https://docs.microsoft.com/en-us/azure/information-protection/faqs#what-subscription-do-i-need-for-azure-information-protection-and-what-features-are-included

The link for the licensing datasheet takes you to a 2018 document: https://download.microsoft.com/download/E/C/F/ECF42E71-4EC0-48FF-AA00-577AC14D5B5C/Azure_Information_Protection_licensing_datasheet_EN-US.pdf

with deprecated products. Can you please update to a fresh version?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0547cf-7694-72e8-1c35-05502fc18233
* Version Independent ID: 3bdb8088-8d87-32aa-6252-f3f9c4944adc
* Content: [FAQs for Azure Information Protection (AIP)](https://docs.microsoft.com/en-us/azure/information-protection/faqs#whats-the-difference-between-the-azure-information-protection-classic-and-unified-labeling-clients)
* Content Source: [Azure-RMSDocs/faqs.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/faqs.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @rtrigueiro, thanks for the heads up on this item as well. Like your other issue, I'm going to remove the link to the outdated content for now, and I've reached out to our team for updates so that we can refresh this article.
When we have a new link with updated information, we'll update this page as well.

Thank you very much for your contribution to docs! I'm closing this issue for now, but feel free to continue commenting if you have more feedback.
#please-close

**Comment by batamig** [comment]
Hi @rtrigueiro,
The response I got from our focal points on licensing is that these are the two resources with up-to-date and relevant information:

- https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection

- https://go.microsoft.com/fwlink/?linkid=2139145

Hope these help, and again - thank you for your feedback.
