### ISSUE TITLE
Latest release is shown as preview in download center

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/Azure-RMSDocs#1389]
On this page, version no. 2.12.62.0 is NOT shown as preview but when trying to download the client from download center this version is shown in preview. So this version is in preview or GA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4d7084-e736-2d1a-5376-58c1187a63ff
* Version Independent ID: f4942d95-dd63-6f30-6e69-a129d728068d
* Content: [What's new in Azure Information Protection (AIP) - Version history & support policy](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history)
* Content Source: [Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @prashant1380, thanks for sending your question into docs!
Version 2.12.62.0 is now in GA. If you're still seeing the preview version only, please open a support case so that this can be escalated to the correct teams. 

I'm going to close this issue for now, but feel free to continue commenting if you have additional feedback. 
#please-close
