### ISSUE TITLE
EDITRIGHTSDATA

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/Azure-RMSDocs#1391]
EDITRIGHTSDATA

**Office custom rights: Not implemented.**

Does this mean that we have no ability to prevent others from removing or changing a label of a document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5089be5-ab21-9713-24cf-e88b3de6596f
* Version Independent ID: 00db5cf0-54f1-8a93-1ff9-75c3848e3869
* Content: [Configure usage rights for Azure Information Protection (AIP)](https://docs.microsoft.com/en-us/azure/information-protection/configure-usage-rights)
* Content Source: [Azure-RMSDocs/configure-usage-rights.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-usage-rights.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @SquirrelAssassin, thanks for sending your question into docs. I'll need to check back with the team for the right answer and see if we need any clarifications or updates in this article.

I'm going to close this issue in the meantime and will reply back when we get more clarification.

Feel free to also post your question to our community in [Yammer](https://www.yammer.com/askipteam/), where a number of subject matter experts are available to reply, open a support ticket, or add more comments if you have additional feedback.

#please-close

**Comment by SquirrelAssassin** [comment]
If all tickets are starting to be auto closed ... your defeating the whole purpose of this system. Nothing will get done, no one will follow up. Please don't close tickets before completing the task.

**Comment by SquirrelAssassin** [comment]
Anyone that reads this ... please understand what happens when someone closes an issue before answering it!!!!!!!!!!!!!!

**Comment by batamig** [comment]
Hi @SquirrelAssassin, thanks for coming back to reply.

Please be assured that we didn't "auto-close" this ticket - we closed it manually while we investigated the issue. This helps prevent having duplicate issues open for the same question in multiple systems - we do still stay on top of the question and try to provide an answer when possible.

Here's the answer I got from the Azure Information Protection team:
- In Word, Excel, and PowerPoint, customers can restrict changing a label or removing protection by ensuring that the user doesn’t have EXPORT or full control. 
- In Outlook, full control is required today to change the label/protection.

I hope that helps answer your question. Since this is more on the Office side than Azure Information Protection, if you need more details, please open a ticket for the Office support team describing your scenario.

**Comment by SquirrelAssassin** [comment]
We use co-author on word documents and within outlook.  This doesn't include export or full control.  

All users in our company can change a label I send them when labeled inside of a Office Product.  

The only time that the ability to not remove / change a label is if I use the Unified Label Fat Client directly by right-clicking and then classifying and protecting.  If I apply a label from within a office product, the label can always be removed.
