### ISSUE TITLE
Network Scan Job was removed as option, Microsoft should not recommend configure Network Scan Job

### ISSUE THREAD

**Issue by sergioandreslq** [MicrosoftDocs/Azure-RMSDocs#1449]
[Enter feedback here]
Good afternoon team, 

Microsoft removed the Network Scan Job, however, the AIP documentation continue making reference to the network scan job, even as recommendation from Microsoft.

it is recommended remove the information and recommendation associated with Network scan Job.

Microsoft documentation:
https://docs.microsoft.com/en-us/azure/information-protection/removed-sunset-services#azure-information-protection-analytics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0927bf-7a11-d800-f0ae-a1c0ce4dcb06
* Version Independent ID: ef830f65-1986-830e-be04-95d163d2de6c
* Content: [Tutorial - Install the Azure Information Protection (AIP) unified labeling scanner](https://docs.microsoft.com/en-us/azure/information-protection/tutorial-install-scanner)
* Content Source: [Azure-RMSDocs/tutorial-install-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/tutorial-install-scanner.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @sergioandreslq,

Thanks for opening this issue.  Our network discovery service is still available to users who already have a Log Analytics workspace set up, which is why we've kept this in the documentation. We'll add the relevant note in this article to clarify and appreciate you bringing this instance to our attention.

I'm going to close this issue for now, but feel free to continue commenting here as needed.
Thanks for your contribution to docs!
#please-close
