### ISSUE TITLE
Misleading note, suggests that AIP is dead and replaced

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/Azure-RMSDocs#1482]
The note at the top of this page is misleading.  It asks if I'm looking for Microsoft Purview Information protection, suggesting that Azure Information protection may be an old product or otherwise unlikely to be what I want.  As I understand it, the Microsoft Purview Information Protection name isn't a new product, but a new umbrella name that includes multiple existing products including Azure Information Protection.  So Even if I were full on board with the new branding, when it comes time to learn about and configure the information protection bits of MPIP, Azure Information Protection is what I want. 

Even worse, the second part of that same note refers to the Azure Information Protection unified labelling client being in maintenance mode, and suggests using something else instead of it.  Since this page isn't about the unified labelling client, but the Azure Information Product in general, and since this is a second part of the above note suggesting I might want MPIP, this furthers the suggestion that the AIP product in general is in maintenance mode and not recommended anymore.  

Given that impression, thinking the official docs for AIP say it's dead and replaced by MPIP, you can imagine the crazy loop of reading docs about AIP and MPIP and the universal labelling client vs the built in labels etc I had to go through to figure out that AIP isn't dead, MPIP isn't really a new product at all but just a confusing marketing name, and it was all just a very misleading note?  

At the very least, I would suggest splitting these into 2 separate notes.  Beyond that, explaining the MPIP note further would be very helpful, and the part about the universal labelling client not being recommended anymore might not belong on this page at all... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c72dfc5-ed52-fb68-bcf1-db7ffcc9152f
* Version Independent ID: dab5d4fd-bab4-76d7-fdfe-7ffd487916ed
* Content: [What is Azure Information Protection (AIP)?](https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection)
* Content Source: [Azure-RMSDocs/what-is-information-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/what-is-information-protection.md)
* Service: **information-protection**
* GitHub Login: @aashishr
* Microsoft Alias: **aashishr**

**Comment by aashishr** [comment]
@Krishna ***@***.***> – can you take a look at this?

From: Steve Whitcher ***@***.***>
Sent: Thursday, August 4, 2022 1:49 PM
To: MicrosoftDocs/Azure-RMSDocs ***@***.***>
Cc: Aashish Ramdas ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/Azure-RMSDocs] Misleading note, suggests that AIP is dead and replaced (Issue #1482)


The note at the top of this page is misleading. It asks if I'm looking for Microsoft Purview Information protection, suggesting that Azure Information protection may be an old product or otherwise unlikely to be what I want. As I understand it, the Microsoft Purview Information Protection name isn't a new product, but a new umbrella name that includes multiple existing products including Azure Information Protection. So Even if I were full on board with the new branding, when it comes time to learn about and configure the information protection bits of MPIP, Azure Information Protection is what I want.

Even worse, the second part of that same note refers to the Azure Information Protection unified labelling client being in maintenance mode, and suggests using something else instead of it. Since this page isn't about the unified labelling client, but the Azure Information Product in general, and since this is a second part of the above note suggesting I might want MPIP, this furthers the suggestion that the AIP product in general is in maintenance mode and not recommended anymore.

Given that impression, thinking the official docs for AIP say it's dead and replaced by MPIP, you can imagine the crazy loop of reading docs about AIP and MPIP and the universal labelling client vs the built in labels etc I had to go through to figure out that AIP isn't dead, MPIP isn't really a new product at all but just a confusing marketing name, and it was all just a very misleading note?

At the very least, I would suggest splitting these into 2 separate notes. Beyond that, explaining the MPIP note further would be very helpful, and the part about the universal labelling client not being recommended anymore might not belong on this page at all...

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 8c72dfc5-ed52-fb68-bcf1-db7ffcc9152f
  *   Version Independent ID: dab5d4fd-bab4-76d7-fdfe-7ffd487916ed
  *   Content: What is Azure Information Protection (AIP)?<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Finformation-protection%2Fwhat-is-information-protection&data=05%7C01%7Caashishr%40microsoft.com%7Cc1e48cb0a4214d8ae08a08da765ab709%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637952429238959558%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xG8H9NKGQSsWhIkXOxYigWzHPpnTFF%2Bdt2sGctz4Xjg%3D&reserved=0>
  *   Content Source: Azure-RMSDocs/what-is-information-protection.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FAzure-RMSDocs%2Fblob%2Fmaster%2FAzure-RMSDocs%2Fwhat-is-information-protection.md&data=05%7C01%7Caashishr%40microsoft.com%7Cc1e48cb0a4214d8ae08a08da765ab709%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637952429238959558%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IeiGhTeam0EQ4udhGVS1XWQuN0nxQluuGna74%2F2qZJY%3D&reserved=0>
  *   Service: information-protection
  *   GitHub Login: @aashishr<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faashishr&data=05%7C01%7Caashishr%40microsoft.com%7Cc1e48cb0a4214d8ae08a08da765ab709%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637952429238959558%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=44t5eutEpztfpV7Bedr%2FDiKm0tHJ%2FFX52IZl1la2YQM%3D&reserved=0>
  *   Microsoft Alias: aashishr

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
