### ISSUE TITLE
Two Vertical Scroll bars

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Azure-RMSDocs#186]
The very large number of questions on this page causes a vertical scroll bar to appear that is in addition to the normal scroll bar in the browser. This makes navigation somewhat confusing. It would be helpful if this FAQ page was split into multiple pages.

**Comment by lleonard-msft** [comment]
Hi @DeanGross  - Thanks for the heads-up; we appreciate the suggestion.  The additional scrollbar is displayed because the number of H2 elements is greater than the available space.  

Also, just for future reference, please be sure to link to the specific page in question when filing issues.  That helps folks who are new to the project and do not have the full context of familiarity.

Again, we appreciate the input.
