### ISSUE TITLE
DecryptAttachmentForEncryptOnly not a valid option

### ISSUE THREAD

**Issue by Lari0** [MicrosoftDocs/Azure-RMSDocs#596]
Set-IRMConfiguration -DecryptAttachmentForEncryptOnly $true is not a valid option for Set-IRMConfiguration cmdlet

**Comment by cabailey** [comment]
@lar1c This new parameter was announced on the Azure Information Protection Yammer group earlier this week - see  https://www.yammer.com/askipteam/#/threads/show?threadId=1142872789.  I've not heard of it being a gradual rollout and plenty of people have been reporting positive results when they have been trying out.  I suggest you use the Yammer thread to report it's not available for your tenant so that the engineering team can respond.  I'll see if I can find out anything as well.

**Comment by cabailey** [comment]
@lar1c After investigation, it seems that the rollout is "98-99%" deployed, so you might well be one of the few tenants where this isn't yet available. You can report your tenant details for follow-up, or simply try again later.

**Comment by lar1c** [comment]
Hi Carol
thanks for the info,
my tenant id is a959dce5-9325-4e68-852e-96c0a3665ad6 , or please let me
know where I can follow up on this.
Thank you very much.

**Comment by cabailey** [comment]
@lar1c  Is this still a problem for your tenant?  I'm told the feature is now 100% deployed so if it's still a problem, open a support ticket for investigation.

**Comment by cabailey** [comment]
#please-close
