### ISSUE TITLE
Fix links to SDK documentation from external pages

### ISSUE THREAD

**Issue by mikekaganski** [MicrosoftDocs/Azure-RMSDocs#632]
https://docs.microsoft.com/en-us/windows/desktop/SrvNodes/rights-management and https://docs.microsoft.com/en-us/windows/desktop/SrvNodes/rms-code-samples-and-tools refer to "not-regularly-updated" https://docs.microsoft.com/en-us/previous-versions/windows/desktop/msipcthin2/active-directory-rights-management-services-multi-platform-thin-client-sdk-portal. Please update the links to point to actualized content.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa7826d5-88fa-e8c7-a963-0bcd432e3119
* Version Independent ID: bbd2bd61-4713-b1c4-b2fa-e65fb70c8491
* Content: [Rights Management SDK 4.2 - AIP](https://docs.microsoft.com/en-gb/azure/information-protection/develop/active-directory-rights-management-services-multi-platform-thin-client-sdk-portal)
* Content Source: [Azure-RMSDocs/Develop/active-directory-rights-management-services-multi-platform-thin-client-sdk-portal.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/Develop/active-directory-rights-management-services-multi-platform-thin-client-sdk-portal.md)
* Service: **information-protection**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **alleonar**

**Comment by BryanLa** [comment]
@mikekaganski - Thanks for your feedback.

I've forwarded this to the team that owns the articles you cited. I've asked them to comment on the resolution, and will update the issue once it's resolved.

**Comment by BryanLa** [comment]
@mikekaganski - I received a response back from the team that owns the articles in question.

Basically, because all of the Rights Management SDK docs were placed in the previous versions archive, they are no longer able to update them. This is a policy issue, so at this point there isn't anything that can be done with them.

Hope this helps. Please let us know if you have any additional questions/concerns.

#please-close

**Comment by mikekaganski** [comment]
I'm afraid that my request wasn't clear enough.

I didn't ask for update of the contents of archived pages at https://docs.microsoft.com/en-us/previous-versions/windows/desktop/msipcthin2/active-directory-rights-management-services-multi-platform-thin-client-sdk-portal. I asked to update links in  https://docs.microsoft.com/en-us/windows/desktop/SrvNodes/rights-management and https://docs.microsoft.com/en-us/windows/desktop/SrvNodes/rms-code-samples-and-tools to point to https://docs.microsoft.com/en-gb/azure/information-protection/develop/active-directory-rights-management-services-multi-platform-thin-client-sdk-portal instead of https://docs.microsoft.com/en-us/previous-versions/windows/desktop/msipcthin2/active-directory-rights-management-services-multi-platform-thin-client-sdk-portal (and the same for the other link to SDK 2.1).

**Comment by BryanLa** [comment]
Ah, OK. Let me get back to the same team then, because they should be able to update the 2 articles you referenced. I'll post again when I get a response...

**Comment by BryanLa** [comment]
@mikekaganski - thanks again for the feedback, and apologies for the confusion on this. The team agreed, and will be updating the links to point to the Azure Information Protection versions of the articles, instead of the archived versions. You should see the link revisions sometime today or tomorrow.

#please-close
