### ISSUE TITLE
office 365proplus version support clearly defined

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/Azure-RMSDocs#646]
the content outlines two versions of proplus needed for different features - 1804 and 1807.  work out how to show consistency providing simple version support requirements for the entire AIP/MIP Stack

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5089be5-ab21-9713-24cf-e88b3de6596f
* Version Independent ID: 00db5cf0-54f1-8a93-1ff9-75c3848e3869
* Content: [Configure usage rights for Azure Rights Management - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-usage-rights)
* Content Source: [Azure-RMSDocs/configure-usage-rights.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-usage-rights.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
bakerm00 Office apps have many features that support Azure Information Protection on different levels, and customers might not need all the features and functionality.  That's why we list minimum versions that are needed for specific functionality that has been recently added. For the versions you mention, customers using Track Changes for protected documents might not be using the Encrypt-Only option for emails, and vice-versa.

**Comment by cabailey** [comment]
@msmbaldwin #please-close
