### ISSUE TITLE
unsecure!

### ISSUE THREAD

**Issue by TobiReykkoenen** [MicrosoftDocs/Azure-RMSDocs#658]
Scenario: an encrypted, high confidential mail is send to Some.One@gmail.com, permission is set to recipient only. The mail is received by the gmail app on Some.Ones mobile. On the same mobile the Azure Information Protection app is installed. 

Some.One does not have an Office 365 account but his friend, Another.One has.
Now Some.One opens the AIP app and asks Another.One to sign in to AIP with his credentials (which of course differ from the receipients mail address). 

Will the app open and show the high confidential message? 
Yes it will! Really Microsoft?! High confidential, high secure..?

**Comment by cabailey** [comment]
@TobiReykkoenen Thank you for your feedback and we always encourage deep thinking and testing to confirm that the product can meet your business requirements.  For your scenario to succeed, the user's identity is compromised: "Some.One … asks Another.One to sign in to AIP with his credentials." You're correct in that Azure Information Protection is not designed to protect against scenarios where users give their credentials to other people.

You can read more about how Azure Information Protection relies on identity management in this documentation: https://docs.microsoft.com/en-us/enterprise-mobility-security/solutions/azure-information-protection-securing-data#identity-based-security

For example,"The basis of protection in Azure Information Protection is that access to protected content is based on authenticated identity and authorization." In your scenario, because Some.One gave away their identity to Another.One, that is why authentication and authorization succeeded.  

In addition: "Securing identities falls outside the scope of Azure Information Protection, and falls in the realm of administrator responsibility."

**Comment by cabailey** [comment]
@msmbaldwin #please-close
