### ISSUE TITLE
pls check note for macos

### ISSUE THREAD

**Issue by martinagrom** [MicrosoftDocs/Azure-RMSDocs#693]
from this site: https://docs.microsoft.com/en-us/azure/information-protection/faqs-rms#how-do-i-configure-a-mac-computer-to-protect-and-track-documents it looks like it is no longer necessary that the customer has to download the client for macos

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c744cf2-5e29-11c4-8e30-9af0adfaa8da
* Version Independent ID: 708c51d5-946a-c162-fcdc-7a4e309ba855
* Content: [Azure Information Protection client : Install & configure](https://docs.microsoft.com/en-us/azure/information-protection/configure-client)
* Content Source: [Azure-RMSDocs/configure-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-client.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@martinagrom Thanks for your feedback. The FAQ entry refers to Office for Mac, which supports protecting Office documents and opening protected Office documents. The RMS sharing app for Mac is slightly different in that it supports opening non-Office files that are protected, which is why it remains as an available download. 

The file types supported by the RMS sharing app for Mac: ppdf, .ptxt, .pxml, .pjpg, .pjpeg, .ppng, .ptiff, .pgif, .pbmp, and .pfile file extensions.

**Comment by cabailey** [comment]
@msmbaldwin #please-close
