### ISSUE TITLE
Are versions 2019 of Office servers supported?

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/Azure-RMSDocs#694]
Does this connector support Ex 2019, SP 2019, S4B 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b55a4732-05a2-40b2-8f7a-d96f6e91bc56
* Version Independent ID: 0e1d4e72-6bf8-cd63-6e48-fa065e10c21a
* Content: [Server support for Azure RMS data protection  - AIP](https://docs.microsoft.com/en-us/azure/information-protection/requirements-servers)
* Content Source: [Azure-RMSDocs/requirements-servers.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/requirements-servers.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Larryngolog  No, not listed as supported because not yet tested.  When I get confirmation from engineering, I'll update these docs.

**Comment by cabailey** [comment]
@msmbaldwin #please-close

**Comment by ChristerEklundh** [comment]
Still no updated documentation from MS saying Sharepoint 2019 is supported with the RMS Connector. So is it supported or not... ?
Thanks!

**Comment by cabailey** [comment]
@ChristerEklundh  That's correct - the documentation isn't updated because SharePoint 2019 has still not been tested with the RMS connector.  So not supported.

**Comment by anoopras4** [comment]
@cabailey, do you know if anyone is going to test it? any work in progress?

Its a showstopper for people using this feature in SP 2016 and trying to upgrade to SP 2019.

**Comment by cabailey** [comment]
@anoopras4  To the best of my knowledge, there are no current plans to test it, I'm guessing because most of our customers are moving to SharePoint Online rather than upgrading to SharePoint 2019, and using labels that apply protection rather than the older SharePoint IRM technology. There's a UserVoice entry for this that you're welcome to add your vote and voice to: https://msip.uservoice.com/forums/600097-azure-information-protection/suggestions/36901315-azure-rights-management-connector-supportablity-fo  If it's preventing your upgrade, you might also want to raise this with your Microsoft Account Manager.
