### ISSUE TITLE
OutlookDefaultLabel doesn't work

### ISSUE THREAD

**Issue by mittulmehta** [MicrosoftDocs/Azure-RMSDocs#721]
I tried to set this option with a label id using just the GUID, but it didn't take. The setting of None worked perfectly. Also, do I have to set the policy at the global level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ae0fec-f7a5-e963-b304-f55755cfd3db
* Version Independent ID: bfed1edd-3fee-0ea1-b478-ddcc76e2adc3
* Content: [Custom configurations for the Azure Information Protection client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-customizations#how-to-configure-advanced-client-configuration-settings-in-the-portal)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-customizations.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-customizations.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@mittulmehta I'm not aware of any problems with this advanced client setting to specify a default label for Outlook, even though it's still in preview.  So if you continue to have problems, please raise a support ticket for investigation.

Advanced client settings apply at the policy level so if you want this setting for all users, apply it at the global policy.  If you want it to apply to a subset of users, apply it to a scoped policy for just those users but obviously, that scoped policy must also include the label that you're specifying.

Are you sure you're specifying a label that users could apply themselves?  For example, if you specify a label ID and users cannot apply that label themselves because it's not in their scope or they see a sublabel for the label you have specified, either of these could result in the symptoms you describe.  If users can manually select the label in Outlook, you should be able to specify the same label for this advanced client setting.

**Comment by cabailey** [comment]
@mittulmehta If it's not working as expected, please do open a support ticket.  But from your description, I'm not sure which label you're trying to set as the default label for Outlook - I assume must be A, C, or D and users can manually see and apply the label? Before you open the support ticket, also confirm that the changed policy is downloaded by restarting Outlook.

**Comment by mittulmehta** [comment]
I'm also a bit confused by the comment that this is in Preview. I don't see anywhere where that is stated? Also, i've raised a support ticket, but want to be sure that the functionality is as specified. I have 4 policies in place today and have attempted to add the setting in different policies.

**Comment by cabailey** [comment]
@mittulmehta My apologies, this setting is no longer in preview (it was for quite a long while).  If it had been, it would be noted in the first paragraph.  If the same users can select the sublabel in Outlook, I don't know of any reason why it wouldn't work for this setting.

**Comment by cabailey** [comment]
@msmbaldwin #please-close
