### ISSUE TITLE
Template Deletion

### ISSUE THREAD

**Issue by sergeyz7** [MicrosoftDocs/Azure-RMSDocs#723]
"However, if you delete a template that has been used to protect content, that content can no longer be opened." - is this statement correct, as it does not appear to make much sense from the technology perspective?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc239db-314a-afdf-2d21-9f2cba07efcd
* Version Independent ID: 31f8cd80-db51-3e11-6f1c-bfaf241deb7c
* Content: [Configure and manage templates for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-templates#to-create-a-new-template)
* Content Source: [Azure-RMSDocs/configure-policy-templates.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-templates.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@sergeyz7 Yes, this statement is correct and why we caution against deleting templates, and also why we don't support this action in the Azure portal where the UI would make it too easy to do this by mistake. 

When you protect content with a template, a reference to that template is embedded in the content so that if you later change the template in Azure (such as add or remove users, change the usage rights), those changes take affect for already protected content.  In other words, there's no need to reprotect the content after you change the template.  This is in contrast to using custom permissions (also known as adhoc protection) where the users and rights are embedded directly into the content at the time it is protected.  So if you delete the template, the reference in the currently protected content remains but the call to the actual template won't work, so the content won't open.

This is an abbreviated version of how templates work for protected content, because clients periodically download templates rather than make a direct call to Azure each time.  And the template isn't necessarily checked each time protected content is opened, because of the use license.  If you're interested in learning more, see https://docs.microsoft.com/en-us/azure/information-protection/faqs-rms#ive-protected-a-document-and-now-want-to-change-the-usage-rights-or-add-usersdo-i-need-to-reprotect-the-document 

In most cases, archiving rather than deleting an old template is the right thing to do.  But if you're sure you don't need to open content that was protected with the template (for example, it was for testing only or you have unprotected the content), then deleting the template offers a healthy housekeeping option.  You might also have to delete templates if you've hit the limit for storing custom templates (500) and need to create more, so you have to delete some templates that you know you don't need.

**Comment by sergeyz7** [comment]
I do really appreciate such a prompt and detail response Carol - and I'm perfectly happy to accept that my previous understanding of the technology might have been wrong (assuming that the service always just decrypts the submitted file manifest and generates usage rights based on it, without making any other calls). However, I must note that your explanation is still inconsistent with my testing - just to make sure, I just now opened a file protected with a template deleted 5 days ago, on 3 different machines, 2 of which have never even had any previous authentications to RMS by users from the domain specified in the template (so there was definitely no possibility of anything being cached locally). How would this fit into the flow you described above?

**Comment by cabailey** [comment]
Your 2 computers - were they previously bootstrapped to Azure RMS so would have downloaded the templates before you deleted them in Azure?  If so, how are you opening the protected content?  Clients refresh templates at different intervals (for example, 7 days by default for Office 2013 and Office 2016).  See https://docs.microsoft.com/en-us/azure/information-protection/refresh-templates  

Can you still see and select the deleted template from these computers?  If you can, the computer has a copy of the template and hasn't downloaded the latest changes.

**Comment by sergeyz7** [comment]
I have deliberately sought to avoid a situation where any previously obtained configuration could affect the results; so one of the machines is my colleague's lab PC, which has never been in any touch whatsoever with my tenant, let alone having the AIP client bootstrapped from it. He has now shut it down, so I cannot confirm whether the deleted template is selectable.
On the other machine, which is Azure AD-joined to my tenant, the deleted template is NOT selectable (I do not see it in the output of _Get-RMSTemplate_ - yet a file protected previously with it opens perfectly fine.

**Comment by cabailey** [comment]
OK, so if the file protected with the now deleted template has not been opened on this computer before (so it can't be using a valid use license), I don't have an explanation that fits with how it's documented. Can you confirm how you're opening the file - for example, natively in Office, or in Office with the Azure Information Protection client installed?  Since you've posted the same question to the [Yammer site](https://www.yammer.com/askipteam/threads/1210864621), let's see what answers you get there.

**Comment by sergeyz7** [comment]
Yes, I could not reconcile this behaviour with the documentation - hence my original question. Answering your question, all the machines I tried opening the file on _do_ have the AIP client on them.
Happy to wait for feedback on Yammer - but in any case thanks for your time so far!

**Comment by cabailey** [comment]
As you can see from the update on Yammer, we dug up some tribal knowledge that helps to explain both the documentation and what you're seeing: Saying the protected content cannot be opened was the original behavior when Azure RMS was first released. Then, a later version of the SDK added an option to include a (signed) copy of the template details into the protected file and this copy could be used if for some reason, the original template in Azure cannot be used - for example, it's deleted.  This fallback option offers parity with AD RMS behavior, and helps to ensure that a protected file can always be opened by people that have been authorized to open it.  

The disadvantage of this behavior is that if you modified the template after protecting a file by adding or removing people, or change the usage rights, those changes are obviously not reflected in the file unless you reprotect the file with the template.  That's often not practical, and one end result could be people you removed from the template can still open the file.  Another example is that people can edit/print/copy from the file that you now want to be view-only.

Because protected content might not have an admin's intended changes, and this copying the template settings into the file is an option provided by the latest SDK (protection can be applied without it), we still advise customers to not delete templates.  

The change from the original implementation wasn't well communicated, and it's an option that the vendor needs to implement, but now it's come to light I'll update the documentation to take all this into account.

**Comment by sergeyz7** [comment]
Thanks for your time and effort Carol - good to see it updated, happy that we have more clarity now!

**Comment by cabailey** [comment]
@msmbaldwin #please-close
