### ISSUE TITLE
Unable to connect to Azure RMS through Azure Cloud Shell

### ISSUE THREAD

**Issue by SaurabhSharma-MSFT** [MicrosoftDocs/Azure-RMSDocs#740]
Hi,

I have tried using the "Connect-AadrmService" on Azure Cloud Shell, however, I am getting the below error-
![image](https://user-images.githubusercontent.com/38112130/51064769-3f324100-15b6-11e9-8186-25e748c69b06.png).
The Module gets installed and I also get the version of the AADRM Module as you can see in the below screenshot - 
![image](https://user-images.githubusercontent.com/38112130/51064826-8587a000-15b6-11e9-9c26-29ea7cf257cb.png)

This command works fine in Windows PowerShell or Windows PowerShell ISE once after installing the AADRM module. Is this command only works for Windows PowerShell ?
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfe8cb1-233a-9187-03a7-701cb35186ed
* Version Independent ID: b7114338-1fae-d000-ddc0-c5eb785c12ba
* Content: [Install PowerShell for AADRM - AIP](https://docs.microsoft.com/en-us/azure/information-protection/install-powershell)
* Content Source: [Azure-RMSDocs/install-powershell.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/install-powershell.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @SaurabhSharma-MSFT  That's correct, the AADRM module does not support Azure Cloud Shell, which would require coding changes.  Because this is product feedback rather than documentation feedback (the page specifically references Windows PowerShell), please use the "Product feedback" option rather than "Content feedback" if you want to request this change with the engineering team.

**Comment by cabailey** [comment]
#please-close
