### ISSUE TITLE
Adoption/Change Management

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/Azure-RMSDocs#755]
I would love to see information in this article that prepares an IT Admin to help communicate to the business as part of the deployment process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8eb9a0-a91e-fcd7-883d-5371b8c8cfe1
* Version Independent ID: a16e9d16-0fc9-793c-820f-0cac8f7815bd
* Content: [Azure Information Protection deployment roadmap](https://docs.microsoft.com/en-us/azure/information-protection/deployment-roadmap)
* Content Source: [Azure-RMSDocs/deployment-roadmap.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deployment-roadmap.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
I understand why you're asking for this information, but it's hard to provide something in the technical documentation that will work for everybody when there are so many variables.  For example, you can deploy Azure Information Protection with labeling, or without.  With classification only, or with protection.  Allow users to specify their own permissions, or not.  With manual labeling, recommended labeling, automation - or a combination.  Different organizations will have differently named labels, different policy settings etc.  No deployment of Azure Information Protection will be the same. 

I wasn't sure from "to the business" whether you meant communication to management, or to users.  For users, we do have a downloadable customizable user guide, Azure Information Protection End User Adoption Guide (https://download.microsoft.com/download/7/1/2/712A280C-1C66-4EF9-8DC3-88EE43BEA3D4/Azure_Information_Protection_End_User_Adoption_Guide_EN_US.pdf).  If you haven't already seen that, it might provide a good starting point.  Our Customer Experience Engineering team is also collating information from customer deployments that I'm hoping they will share in a future blog post - such as communication with stakeholders as part of the deployment process, and help prepare end users with email notifications and posters for their chosen labels and selected user experience. 

Because this is a journey and we're all learning, I also encourage you to tap into our community expertise and experience on Yammer (https://www.yammer.com/AskIPTeam).

**Comment by DeanGross** [comment]
Karuana Gatimu at MS has created an Adoption and Change Management program (and course on edX) that is focused on Teams. I wonder if that could adapted/expanded to include AIP and other Security/Compliance products, see https://courses.edx.org/courses/course-v1:Microsoft+CLD277x+3T2018/courseware/7d691e77a1e84eaf85a2114b3891977a/0ebc636074f24925a2f6c80d3f3ce21c/3?activate_block_id=block-v1%3AMicrosoft%2BCLD277x%2B3T2018%2Btype%40vertical%2Bblock%40cce74a9aa1034f1dab890e4d2d116b71

**Comment by cabailey** [comment]
If you didn't see the Yammer announcement, the tactical guidance that I mentioned is now available: https://techcommunity.microsoft.com/t5/Azure-Information-Protection/Azure-Information-Protection-Deployment-Acceleration-Guide/ba-p/334423

**Comment by cabailey** [comment]
#please-close
