### ISSUE TITLE
Capacity of RMS Connector

### ISSUE THREAD

**Issue by kartik36524** [MicrosoftDocs/Azure-RMSDocs#763]
Hi Team, 

What is the capacity of RMS Connector. If we have a user base over hundred thousand, how many connectors are to be deployed for Exchange and Sharepoint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98397d63-e9a3-a620-9efc-bfd3371a3c61
* Version Independent ID: 652e8b33-90e0-aad6-3238-fc8b41eda674
* Content: [Install & configure the Rights Management connector - AIP](https://docs.microsoft.com/en-us/azure/information-protection/install-configure-rms-connector#configuring-load-balancing-and-high-availability)
* Content Source: [Azure-RMSDocs/install-configure-rms-connector.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/install-configure-rms-connector.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@kartik36524 You shouldn't need to worry about capacity when deploying the RMS connector but for redundancy purposes, always install at least two. Here's a technical explanation from engineering why this shouldn't be a problem:

"FCI and SharePoint Server generate a load of approximately one call per month per server (they only need a monthly certificate renewal since they only protect content which is an online operation, and in the case of SharePoint it only consumes content protected by itself which uses the embedded owners license, again not needing a service call), so their load is completely negligible even in the largest environments. 

Exchange is different as it actually calls the RMS service (usually twice) for every protected email each user receives. Even then, the connector can handle large numbers of licensing operations, since it doesn't do local cryptographic processing or policy analysis and it only passes requests through to the cloud with minimal processing. In essence, it is not CPU or memory bound, it is only network bound. A typical licensing operation takes less than 100KB, so a 1GBps network link should be able to handle several hundred requests per second, which should be sufficient for even the largest environments. We still recommend having more than one server for fault tolerance purposes, and if there are Exchange servers in multiple locations it is often recommended (though not strictly necessary) to have RMS connectors at each of them.

So in essence [to answer question about sizing recommendations], the minimal server that Windows Server will support, plus a bit of memory for supporting IIS and a good network connection should be all you need, two of them for redundancy."

**Comment by cabailey** [comment]
@kartik36524 If this answers your question, I will ask for this issue to be closed.

**Comment by cabailey** [comment]
#please-close
