### ISSUE TITLE
Please make clear that this document does NOT apply for O365/Sharepoint online documents

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/Azure-RMSDocs#784]
Hi , 
You do indeed have this small font single line that says "To scan and label files on cloud repositories, use Cloud App Security." and strictly speaking that implies that one who wants to scan cloud documents should not install nor configure this AIP scanner.  

Please make this document much clearer by saying as a seperate section something like  "DO NOT USE THIS SETUP TO PROTECT CLOUD DOCUMENTS BUT USE CLOUD APP SECURITY".  The Diagram too gave me the confusing impression that AIP scanner would be used to protect documents in the cloud with the arrow pointing from the AIP scanner to the cloud.   

Myself and a very smart Microsoft support engineer spent many hours figuring this out, and working on an installation that was in the end useless.

Thank you
Bart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9c09ab-9d9a-5329-be18-626ab19725d1
* Version Independent ID: e6110fa2-11ac-500b-79de-95ca948159a9
* Content: [Deploy the Azure Information Protection scanner](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi Bart Sorry to hear about your bad experience. Can you please share your ticket reference?

**Comment by cabailey** [comment]
The sentence "To scan and label files on cloud repositories, use Cloud App Security." has been changed to "To scan and label files on cloud repositories, use Cloud App Security instead of the scanner." This should help clarify that Cloud App Security is an alternative solution, rather than part of the scanner deployment.

Our technical documentation focuses on what our products can do rather than what they can't do. We included the extra sentence about using Cloud App Security for cloud-based data stores to help customers identify the right solution if they have those data stores, but this information doesn't warrant its own section in this article. The sentence that you referred to as having small font is the standard text size we use for our documentation and we do not use all capitals for emphasis. Many people interpret all capitals as unnecessarily shouting, and it doesn't localize for all languages.

After carefully reviewing the article, we do not think additional clarifications are needed for SharePoint Online not being supported by the scanner:
- The introduction states in a bulleted list the different types of data stores that the scanner supports - which calls out SharePoint Server versions, and does not refer to SharePoint Online.
- The diagram does have an arrow from the scanner to the cloud, but it points to an icon for Azure Information Protection with the description "Azure Information Protection with a policy that is configured for automatic classification and optionally, protection". There is no icon for Office 365 and no mention of SharePoint Online. 
- The prerequisites table includes a row specifically for SharePoint, which lists the SharePoint Server versions supported (2016, 2013, 2010) with the text "Other versions of SharePoint are not supported for the scanner."
- The SharePoint Server version numbers are repeated again in the "Specify data stores for the scanner" section.
- The online help that is referenced in this article is also clear about the SharePoint Server versions supported and the examples help to highlight this.
- The article has no references to Office 365 or SharePoint Online.

This article has been published (including the same diagram) since October 2017 with thousands of page views each month, and this is the first time we've heard the feedback that it implied the scanner supported SharePoint Online. Thank you for sharing your experience and we'll continue to monitor feedback.

I'm sorry that you had a bad experience trying to deploy the scanner for something that it doesn't support, and that the support engineer you spoke to wasn't able to quickly correct this misunderstanding.  It's very important that our support teams have good knowledge about the products they support, so as requested previously, please share your support ticket reference for us to follow up on this.

**Comment by blouwagie** [comment]
Thank you for this very careful and thoughtful response. I concur with your
conclusion with one generic remark: Microsoft documentation of often
confusing because it does not explain how a given product fits in with
other products.
I really really appreciate your response and there is indeed a lot of good
information on the document. A lot of people searching to understand this
solution would result in thousands of page views. It takes energy to give
feedback and more energy to respond. Hopefully all with the same aim of
improving understanding for the next reader.
The arrow that points to the cloud indeed points to an azure symbol, clear
for those who already understand.
With apologies for brevity as I'm writing this on my phone.
Regards
Bart


Bart Louwagie
Holmes, NY
bart@louwagie.com
845 202 0239 (google voice)

http://louwagie.com
https://www.linkedin.com/in/bart-louwagie/

(when conference call is needed)

**Comment by orbarak-ms** [comment]
@blouwagie Hey Bart. My name is Ory and I'm an Escalation Engineer of Azure Information Protection.
Could you please share the ticket number you had with support so we could review it and improve our services to the customers?
Feel free to reach me via email if it's more comfortable for you, orbarak@microsoft.com

**Comment by cabailey** [comment]
#please-close
