### ISSUE TITLE
Microsoft has the hardest time deciding on nomenclature

### ISSUE THREAD

**Issue by ejacobsen-glofin** [MicrosoftDocs/Azure-RMSDocs#822]
You guys have the most confusing naming conventions, please start picking names with differentiations and sticking with them. "Templates", referenced everywhere in the Information Protection documentation, are now "Labels". "Microsoft Store" to "Windows Store". "Beam" to "Mixer". "Team Services" to "Dev Ops". OneDrive, OneDrive for Business, and SharePoint. I work in IT and it's hard to keep track of all this, I can only imagine the confusion for the average end user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc239db-314a-afdf-2d21-9f2cba07efcd
* Version Independent ID: 31f8cd80-db51-3e11-6f1c-bfaf241deb7c
* Content: [Configure and manage templates for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-templates)
* Content Source: [Azure-RMSDocs/configure-policy-templates.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-templates.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@ejacobsen-glofin  I hear you, and I will pass on that feedback to our teams who are responsible for naming and branding. I can't speak for the other products, but I did want to clarify that templates and labels are not the same thing, renamed. 

I know this can be confusing because labels that are configured for protection automatically create a template with the same name.  So they can look as if they are the same, but they are not.  A label can contain (or reference) a template.  But you can also have a template independently from a label, and you can have a label without a template.  This article is specifically for managing templates, which for example, can be relevant for customers with an Office 365 subscription but not a subscription for Azure Information Protection.  You can also create templates by using the ADDRM PowerShell module.

To give a practical example:  Outlook on the web doesn't support labels, only templates.  Whereas Outlook does support labels, which can be configured for protection or without. So if you have a label named "Confidential" that applies protection, you see a "Confidential" template in Outlook on the web, and a "Confidential" label in Outlook.  Both will apply the same protection, but only the label can apply label settings such as headers and footers, or detect sensitive information.  If you have a label named "General" that doesn't apply protection, it won't appear in Outlook on the web but will appear in Outlook.

I hope that helps to explain the difference between labels and templates for Azure Information Protection.  

Because terminology can be very confusing, especially because of changes as products evolve, Azure Information Protection has a terminology page where we also list alternative names: https://docs.microsoft.com/en-us/azure/information-protection/terminology

**Comment by cabailey** [comment]
I'm assuming I can ask for this issue to be closed now?  If not, you can always reopen.
#please-close

**Comment by ejacobsen-glofin** [comment]
Can be closed

Sent from my iPhone

On Apr 2, 2019, at 6:23 PM, Carol Bailey <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm assuming I can ask for this issue to be closed now? If not, you can always reopen.
#please-close
