### ISSUE TITLE
Title is shortened

### ISSUE THREAD

**Issue by alisalih1** [MicrosoftDocs/Azure-RMSDocs#824]
Please update the title to reflect the content of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8021a68-b55b-93eb-5fd0-abbbf8f5da58
* Version Independent ID: e246079c-8579-0bdc-b7c8-290114e8fa1a
* Content: [Azure Information Protection also known as](https://docs.microsoft.com/en-us/azure/information-protection/aka)
* Content Source: [Azure-RMSDocs/aka.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/aka.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @alisalih1  Can you explain what you think needs updating and why?  If you are referring to the ellipsis ( "...")  after the "also known as", this was deliberate because this product has had many names and we can't put them all into the title.  So the ellipsis is used to denote that this product has had many alternative names.

**Comment by alisalih1** [comment]
"also known as" doesn't communicate what the article is about. 

I think something more descriptive needs to be in the heading, something like "Terms related to Azure Information Protection" or something else. You'd want to give the reader a sense of what the article is and the purpose with a use of heading.

**Comment by cabailey** [comment]
The page isn't about terms - it's scoped to alternative names for the product "Azure Information Protection" that people might know or see in documentation, the UI, or logs. So for example, Azure Information Protection is also known as Azure Rights Management, Azure Rights Management service, Azure RMS, Windows Azure Active Directory Rights Management. And the list goes on. If it only had one alternative name, we could include that in the title, but the list is too long (denoted with the ellipsis) and we can't know which name(s) somebody might see or know.

The first paragraph and metadata description, where we don't have the same character length restriction of a title, provides additional information what to expect from the page contents.

We have a separate page for terms - https://docs.microsoft.com/en-us/azure/information-protection/terminology. That page does include alternative names for the product. But we put this page together to specifically address the branding confusion for this product because we see a lot of confusion about this.

**Comment by alisalih1** [comment]
I said "terms or something else". You completely ignored the point that heading should be as descriptive as possible. I am done here.

**Comment by cabailey** [comment]
Thanks for the interesting discussion. The GitHub Issue was filed as "Title is shortened" with the comment "Please update the title to reflect the content of the page". I thought I had addressed both of those, that the elipsis indicates there is more than one product name, abbreviation, feature name, or other related names that people might know or see for Azure Information Protection - and hence the "also known as" phrase in the title after the product name. I'm not seeing how the title doesn't reflect the content of the page, and I haven't seen a viable alternative title suggested. Where we don't have such a restrictive number of characters, there's a fuller description in the first paragraph, also in the metadata description. 

You say you're done with this thread but I'll ask for it to be left open for a while to see if others agree that this page needs retitling and for alternative suggestions. The guidance we have for titles is 59 chars or fewer including spaces, and include the full product name.
