### ISSUE TITLE
AIP with Multi-Geo tenant

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/Azure-RMSDocs#830]
Our organization will be implementing the Multi-Geo feature.  Does AIP/RMS automatically follow to the satellite Geo's as they are implemented ?  If not, what actions are needed to provide uniform classification / protection across the organization?

**Comment by aashishr** [comment]
AIP will continue to be configured at the central location. There will be a single AIP configuration for the central tenant and the satellite geos. In that sense, there is a uniform classification/protection across the organization already :)

If there is a need to provide certain labels _only_ for a satellite geo, then use a different policy to scope the labels to specific users.

**Comment by bholzmmc** [comment]
When there is a label or policy update (add/change/delete) what expectation regarding delay or latency is to be expected for the change to be visible across all geos ?

**Comment by cabailey** [comment]
@bholzmmc Is your question from the admin perspective for managing the labels/policy settings, or the user perspective for seeing/applying the labels?

If it's from the admin perspective, you should see the changes for Azure Information Protection in near real-time because of the answer that Aashish gave you. If you are using unified labels that you publish from the Office 365 Security & Compliance Center, I'm told there's a slight delay because of caching, but it's not related to geos.

If it's from the user perspective, there are different triggers to download any changes to labels and policy settings, but again, it's not geo-related. For the Azure Information Protection client, these triggers are documented here: https://docs.microsoft.com/en-us/azure/information-protection/configure-policy#making-changes-to-the-policy

**Comment by bholzmmc** [comment]
I guess I need a better understanding of how services like AIP are actually deployed and operate in a multi-geo environment.  I.e. are the replica's of the service instantiated in each geo ?  Can you provide guidance to where I might find such details ?  Then I'll come back with more pointed questions if any remain.

**Comment by cabailey** [comment]
@bholzmmc I'm told there's nothing different to document for this scenario, so since your questions are technical rather than about the documentation, please use the Azure Information Protection Yammer site to continue this discussion: https://www.yammer.com/askipteam

**Comment by cabailey** [comment]
#please-close
