### ISSUE TITLE
Direct label creation in SCC

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/Azure-RMSDocs#831]
What about if we have created labels directly in SCC without using any encryption and using only AIP unified labeling client which is in preview. And in AIP portal no labels exists and migration step is also not performed. Can we rely on this approach? Or is it must to have the same labels in AIP portal also?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b8e206-aa49-f558-09d4-506f5c725337
* Version Independent ID: 5169a618-9dea-3349-c365-0b16b57560c6
* Content: [Migrate Azure Information Protection labels to the Office 365 Security & Compliance Center - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels?WT.mc_id=twitter#feedback)
* Content Source: [Azure-RMSDocs/configure-policy-migrate-labels.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-migrate-labels.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@prashant1380  If you have no labels in the Azure portal, there is nothing to migrate. If you don't need the Azure Information Protection client and will only use unified labeling clients, then there's no reason to create labels in the Azure portal. Only if you also want to use the Azure Information Protection client (with the same labels), should you create labels in the Azure portal and then do the label migration.

**Comment by prashant1380** [comment]
Great.. thanks for clarifying my doubts. I am hoping that all of the labels configuration settings will eventually be available in SCC. We decided to go for this approach because we have just started using labels.

**Comment by prashant1380** [comment]
One additional query. Can we use security groups (not mail enabled) to publish sensitivity labels policy to a target group?

**Comment by cabailey** [comment]
Your strategy of using just the Security & Compliance Center seems sound if you've only just started to use labels and don't immediately need the features or behavior of the Azure Information Protection client.  Especially if you have already created labels in the Security & Compliance Center.  If you hadn't created any labels, another approach for new customers is to migrate the default labels from the Azure portal, because you don't get any default labels with the Security & Compliance Center.  For many customers, the default labels are a great way to get up & running quickly instead of having to create labels from scratch.

If you have questions about publishing sensitivity labels in the Security & Compliance Center, please use their documentation and ask clarifying questions there if you can't find the answer.  Start here: https://docs.microsoft.com/en-us/Office365/SecurityCompliance/sensitivity-labels

For groups, Azure Information Protection always uses email-enabled groups in Azure AD. If you want specifics, see https://docs.microsoft.com/en-us/azure/information-protection/prepare#azure-information-protection-requirements-for-group-accounts

**Comment by cabailey** [comment]
@prashant1380 I'm assuming I can ask for this issue to be closed now?  If not, you can always reopen.
#please-close
