### ISSUE TITLE
"Azure (cloud key) with template" missing option in table

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/Azure-RMSDocs#833]
Hi,

In the table titled "Comparing the behavior of protection settings for a label" I do not see the option for "Azure (cloud key) with template" (not custom permissions). That is the option we are currently using in pilot phase and we have been testing that with the "Azure Information Protection unified labeling client".   The labels are visible in that case, at least in all our recent testing.  That is the setting we hope to move forward with for several organisations. I hope that the option missing in this document does not mean that this option will be removed in the future. If we are indeed on the right path, can you please add "Azure (cloud key) with template" as an additional row in this table? Thank you
Bart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b8e206-aa49-f558-09d4-506f5c725337
* Version Independent ID: 5169a618-9dea-3349-c365-0b16b57560c6
* Content: [Migrate Azure Information Protection labels to the Office 365 Security & Compliance Center - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels#comparing-the-behavior-of-protection-settings-for-a-label)
* Content Source: [Azure-RMSDocs/configure-policy-migrate-labels.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-migrate-labels.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi Bart - are you referring to the configuration option "Set permissions" or "Select a predefined template"?

**Comment by cabailey** [comment]
@blouwagie  Yes, I understand what you're asking but unlike HYOK with a template, there are two different ways to configure Azure cloud key with a template - using "Set permissions" and "Select a predefined template" . That was why I asked you because the answer for why it's not in the table is different:

For a label that's configured with "Set permissions", there are no differences across the clients and therefore this configuration isn't in the table that's introduced with "Protection settings that behave the same way are not listed."  The table is to compare differences across the clients to help you choose which client to deploy for the outcome you want.  So although we tested this configuration, we omitted it from the table so you didn't have to compare all 3 columns trying to work out what was different, only to conclude nothing was different.  I'm guessing this is the configuration you used, so you don't need to worry about this when deciding which client to use.

For a label that is configured with "Select a predefined template", it doesn't belong in this table because it's not supported by the Security & Compliance Center (with no plans to do so).  In our label migration guidance, we include instructions for changing this configuration to "Set permissions" before the label migration.  We don't include this configuration in the table because it would be confusing after the instructions to change it.

**Comment by blouwagie** [comment]
Hi @cabailey , I understand your reasoning for eliminating the ones where the behavior does not differ between the clients. That suffices for readers who already know a lot about how clients behave. Please realize that many readers do not have that knowledge. So just knowing how a client behaves even if the different clients behave the same way would be more than useful. 

In general, please:, 
1. if/when you eliminate tested configurations like you did here, please as least indicated in the document that you did so.
2. Even better would be to have a link to the list that does include other scenarios that you decided to eliminate so we could catch with "you who already know". That way we'd be able to know what the client behavior is and we would see that there are scenarios where not every client acts differently. Currently the document leaves a strong impression of "messy" differences between clients. Whereas if you would have left the other scenarios in, we'd know to chose the scenario with consistent behavior (if it matches our needs).
3. Guide us to to help chose a path, not only how to once you have chosen a path. 

I do not at all understand your last paragraph.  Maybe you are saying the the predefined templates such as [personal, public, internal, confidential, highly confidential] do not work with SCC, but I did set up Unified labeling and those labels DO show and could be published there. Maybe I do not know what [a label that is configured with "Select a predefined template"] means.

**Comment by cabailey** [comment]
Hi @blouwagie Thank you for your feedback.  Obviously, the desired goal for everybody is parity in features, parity in behaviors. But that's not currently in place, so we're letting people know what the differences are today, and they can decide for themselves which client to use.  We do have guidance which client to use here: https://docs.microsoft.com/en-us/azure/information-protection/faqs-infoprotect#which-preview-client-do-i-install-for-testing-new-functionality

For the protection settings, there are too many configuration variables to list them all and if we tried, would lead to "documentation bloat" in this migration article - lots of text that doesn't add much value because it's not need-to-know information. If you want to know how the individual protection settings work, we have that documented elsewhere: https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-protection#to-configure-a-label-for-protection-settings  

However, I did realize that the statement "Protection settings that behave the same way are not listed." was not entirely correct, so this is now qualified with two exceptions - that labels will not display in File Explorer if you only have native Office labeling (by design) and the known issue with the Encrypt-Only option that is expected to be fixed.

To check how your labels are configured, view their settings in the Azure portal and use the documentation for more information about the options (again, https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-protection#to-configure-a-label-for-protection-settings).  If you do not see the option for "Select a predefined template" on the Protection blade, but do see settings for "Set permissions", you do not need to worry about this label configuration when you migrate labels to Office 365.

For some background information: When Azure Information Protection first came out, you could create a label that linked to an existing template, rather than be part of the label. So for example, you could have a label named Confidential that linked to a template with a completely different name.  You could then reuse that template with multiple labels. This type of configuration has been phased out and only in specific circumstances will you be able to have this label configuration.

With the current default Azure Information Protection policy (details here https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-default#current-default-policy), there are two labels that are configured for protection that both use the "Set permissions" option, which automatically creates a template with the same name as the label. There are no problems migrating these labels and you can publish them for use. To clarify, the default labels of Personal, Public, and Internal do not have protection templates associated with them.

**Comment by cabailey** [comment]
No further updates.
#please-close
