### ISSUE TITLE
AIP Scanner and Unified Labeling

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/Azure-RMSDocs#843]
Does the AIP Scanner support unified labeling? Or will require SCC labels to be synced and published?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b8e206-aa49-f558-09d4-506f5c725337
* Version Independent ID: 5169a618-9dea-3349-c365-0b16b57560c6
* Content: [Migrate Azure Information Protection labels to the Office 365 Security & Compliance Center - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels#clients-and-services-that-support-unified-labeling)
* Content Source: [Azure-RMSDocs/configure-policy-migrate-labels.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-migrate-labels.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Mark7even The unified labeling client doesn't yet support the scanner.  You can find a comprehensive list of what's supported/not here: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#feature-comparisons-for-the-clients 

Shorter version included with the release information page: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history

**Comment by Mark7even** [comment]
Can you clarify what it means by the client does not support the scanner? Doesn't the scanner apply labels on its own? The scanner doesn't need the unified labeling client in order to apply labels, correct?

**Comment by cabailey** [comment]
The client has a number of components - for example, the Office add-in, a shell extension for File Explorer, a PowerShell module, a viewer, and the scanner.  Or to put it another way, you can't use the scanner until you have installed the client.

The scanner component is not yet supported by the unified labeling client.  This work is planned, but I can't give you a timeframe.  So for now, you will have to continue with the Azure Information Protection client with labels and policy settings that you configure in the Azure portal.

**Comment by Mark7even** [comment]
This is in reference to the client that needs to be installed on the server running the AIP scanner correct?

**Comment by cabailey** [comment]
Yes, that's right, and why the Azure Information Protection client is listed as a prerequisite for the scanner (https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner#prerequisites-for-the-azure-information-protection-scanner).

If it helps, here's a list of scenarios that the Azure Information Protection client supports: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide#should-you-deploy-the-azure-information-protection-client 

When the Azure Information Protection unified client goes GA, there will be a similar admin guide and list. But for now, because it's still early days for this client, we're just calling out the differences.

**Comment by cabailey** [comment]
Hi @Mark7even I think this issue is now resolved so I'll ask for it to be closed. You can always reopen or open a new issue if you have further questions.
#please-close
