### ISSUE TITLE
Feature Clarification

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/Azure-RMSDocs#845]
Assuming the new Unified labeling client has feature parity, can some clarifications be provided on the following features that will "Not be available":

- Track and revoke from Office apps and File Explorer : These were the only ways I am aware of tracking and revoking (Office apps & File Explorer), so is tracking and revoking being completely deprecated? Will there be a different way to track and revoke or is this going away?

- Offline support for protection actions : Can clarification be given on what this means? Currently the Security and Compliance center has ability allow offline access for a certain amount of time. Is this what is being mentioned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a13e85-78dd-d4e0-30d9-4acc40f3e11a
* Version Independent ID: 09429982-159f-81fd-a989-901142dee148
* Content: [The client for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#feature-comparisons-for-the-clients)
* Content Source: [Azure-RMSDocs/rms-client/use-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/use-client.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
If you have questions about the features that won't be in the unified labeling client, I recommend you ask them on the team's Yammer site (https://www.yammer.com/askipteam) because I can't answer them here.  With this exception for what we know won't be supported, the technical documentation can't include information about future releases.

No offline support for protection actions in File Explorer and PowerShell means when you use these, you must have an Internet connection to protect a file.  The configuration option for offline access you see in the Security & Compliance Center is for consumption - whether a user opening a protected document can view the document when they don't have an Internet connection.

**Comment by cabailey** [comment]
Hi @Mark7even After first publishing the section about the features that won't be in the unified labeling client, the engineering team has had efficient customer feedback that some of the features are now "back on the table" for discussions.  I've removed these from the list and modified the wording to "currently not planned" - so it's definitely worthwhile providing feedback on Yammer, and keeping an eye on this list!

**Comment by cabailey** [comment]
#please-close
