### ISSUE TITLE
Business partners cannot open documents

### ISSUE THREAD

**Issue by mbell85** [MicrosoftDocs/Azure-RMSDocs#848]
I've configured labels using the directions above, but users in some of our partner organizations are unable to view the documents we send to them. For example, I've included tn.gov domain as a co-author but users there are saying they cannot open the documents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4b8020d-3f87-1a2d-74e4-f132640010c4
* Version Independent ID: cb6f52e8-2d35-d899-8011-6f16058490de
* Content: [Configure an Azure Information Protection label for protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-protection#example-5-label-that-encrypts-content-but-doesnt-restrict-who-can-access-it)
* Content Source: [Azure-RMSDocs/configure-policy-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-protection.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@mbell85 There are many variables here, so please open a support ticket for investigation and include (if you can) some information about what version of Office they are using (if an Office document) and on what platform & OS version, confirm they are signed in using an email address with "tn.gov", and exactly what error message they get (screenshots are great, here!).

**Comment by mbell85** [comment]
@cabailey I certainly will do that. When I directed the person to sign up for Azure RMS for Individuals account, they got a message that "Azure Information Protection is currently unavailable for your work or school."

**Comment by cabailey** [comment]
@mbell85 OK, in that case, you're looking at a different set of variables around Azure AD rather than at the application level - but I still recommend you progress this with Support.  In this case, the Office version & platform isn't relevant but having more information about the partner's directory for user accounts will be helpful.  For example, do they have Office 365, single-sign on with on-premises accounts, a government cloud etc.

**Comment by cabailey** [comment]
#please-close

**Comment by mbell85** [comment]
Hey @cabailey. I'm still working with MS support on the issue, but I'm being told that something must be misconfigured in the partner's domain which is preventing them from opening the documents and emails. This sounds about right, as once partners in domains signed up for Azure RMS account for individuals they were able to open successfully. Others are not eligible to sign up and still can't open.

**Comment by cabailey** [comment]
@mbell85 Thanks for the update and yes, the Azure AD side that the partner owns does sound like where this is failing.  However, GitHub Issues are for documentation issues (for example, instructions to configure labels for this scenario were incorrect), not support issues, which is why I recommend we close this now you're progressing this through the correct channel.

**Comment by mbell85** [comment]
I see. Thanks very much.

**Comment by cabailey** [comment]
#please-close

**Comment by mbell85** [comment]
We confirmed it was an issue in the partner's Exchange Online server configuration.
