### ISSUE TITLE
Add-AIPScannerRepository no longer has a -Path parameter

### ISSUE THREAD

**Issue by mhendric** [MicrosoftDocs/Azure-RMSDocs#850]
In version of 1.45.32.0, Add-AIPScannerRepository no longer has a -Path parameter, so the commands in this article don't work. Further, if you run Add-AIPScannerRepository by itself, it says:

WARNING: This cmdlet is deprecated. Please use Azure portal to manage scanned repositories.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bad6e055-5f55-5b2f-1877-e277f2954c66
* Version Independent ID: 7b9f2e2a-0d2e-f541-001d-ff76715314df
* Content: [Quickstart - Find sensitive information in files by using the Azure Information Protection scanner - AIP](https://docs.microsoft.com/en-us/azure/information-protection/quickstart-findsensitiveinfo)
* Content Source: [Azure-RMSDocs/quickstart-findsensitiveinfo.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/quickstart-findsensitiveinfo.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@mhendric  You're using the preview version of the client, rather than the general availability version.  On this page "Note: This quickstart uses the current general availability version of the scanner and not the preview version, which uses the Azure portal for configuration." and the prerequisites also makes this clear by naming the .exe to install ("download AzInfoProtection.exe from the Azure Information Protection page").

When the version of the Azure Information Protection client that you have installed goes GA, the tutorials and quickstarts will be updated.  Meanwhile, because there are so many differences between the GA version and the preview version of the scanner, we have separate documentation during the preview period: https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner-preview

**Comment by mhendric** [comment]
Works for me. Thanks for the quick response! Feel free to close this out.

**Comment by cabailey** [comment]
@mhendric  Thanks for the update.
#please-close
