### ISSUE TITLE
Sublabel and Parent label selection issue

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/Azure-RMSDocs#858]
The following text isn't really true: "When you create the first sublabel for a label, users can no longer select the original, parent label." You can select the original parent label for Office documents by going through File -&gt; Info -&gt; Protect Document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23c06b55-02f9-8539-f41e-e8fb89fae5d9
* Version Independent ID: 16332f0e-d098-a608-5e0f-c71e98e51f5b
* Content: [New Azure Information Protection label - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-new-label#feedback)
* Content Source: [Azure-RMSDocs/configure-policy-new-label.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-new-label.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @terrogin  When you use File -> Info -> Protect Document, you're not seeing labels.  You're seeing protection templates and where you can apply templates is different from where you can apply labels.  I know this can be confusing because labels that are configured with protection settings create templates with the same name, but templates work differently. Labels apply classification and can also apply visual markings such as a header, footer, watermark - protection templates can't do this.  They can only apply protection.

So for example, if you create a sublabel without protection settings, you will not see it under File -> Info -> Protect Document.

**Comment by terrogin** [comment]
That helps, thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cabailey** [comment]
#please-close
