### ISSUE TITLE
Version identification inconsistent

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/Azure-RMSDocs#875]
On this page, the latest version is identified as Version 1.48.204.0 however, when you go to the download page it identifies the version as 2.0.778.0.  This is confusing because after running the upgrade and Dropping down the Help item in the Protection Menu one could expect to see 2.0.778.0 and when seeing 1.48.204.0 may think (as I did) that the install failed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d40811-9908-39df-a632-a31be13d9ad9
* Version Independent ID: b5c3157d-20d1-57d3-5332-41e385ebd7b9
* Content: [Azure Information Protection client - Version history & support policy](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-version-release-history#feedback)
* Content Source: [Azure-RMSDocs/rms-client/client-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-version-release-history.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi again, @bholzmmc

There are now two different clients that you can download and they are both in GA status. The Azure Information Protection client (1.48.204.0)  and the Azure Information Protection unified labeling client (2.0.778.0).  The description at the top of the download page explains when to install each and you'll find more information here: https://docs.microsoft.com/en-us/azure/information-protection/faqs#whats-the-difference-between-the-azure-information-protection-client-and-the-azure-information-protection-unified-labeling-client

I think the problem with the download page is that it doesn't accommodate listing two versions, so it's showing the later version only.  I agree this is confusing when you actually want the other version and feedback has been given to engineering to request that this is fixed.  But it might not be possible.

**Comment by bholzmmc** [comment]
Could the explanatory text on the download page include the specific versions of each and the Version:  above the file list be eliminated or noted as ‘see above’.

Or,

The version numbers be incorporated into the filenames i.e. AzInfoProtection.1.48.204.0.exe  and AZInforProtection_ul.2.0.778.0.exe.

Or,

Separate download pages for the AIP client and the UL client, with descriptive information and guidance to the other where needed.

Or,

The documentation, wherever the client download is referenced advise that the clients have different program versioning.


Just a few ideas off the top of my head.

Brian

**Comment by cabailey** [comment]
@bholzmmc Thanks for your suggestions - let's see if they can add another version number on the download page, first. 

The download page has very specific limitations and requirements for each field, which is the problem we're up against.  It does list the version numbers in the Details section.  The description field at the top is maxed out for the number of characters allowed :)

Version numbers were deliberately kept out of the file names because these will change with each GA release & people often have deployment scripts based on the file name - so we keep these constant for GA releases. 

We previously had a separate download page for the unified labeling client when it was in preview, but consolidated them at GA.  The thinking was that having them on separate pages could infer they were separate products, instead of two clients for the same product - where the Azure Information Protection client will eventually be removed (no date for that, before you ask me!).

You don't need to know what the version number is to install the client - just the file name. But we added information about the version numbers in the FAQ I provided to help identify which client you have installed.  I'm not a fan of peppering the documentation with version numbers that can get out of date, and try to avoid this where possible.

I'll give you an update when I hear back if they can add multiple versions to that field - if not, I'll suggest they add a clarification in the Details section.

**Comment by cabailey** [comment]
@bholzmmc  They allow a total of 16 characters for this field  With this limitation they can just squeeze in "2.0.778,1.48.204" which isn't ideal - is this better than before?  As you will see later in the Details section, both versions are listed separately with the respective clients.  But I'm guessing you didn't see this (not new).

**Comment by cabailey** [comment]
@bholzmmc We've heard from a few other people that they have been confused by the two different clients on the same page. If we keep them on the same page in the Download Center, I think we've done the best we can with the length limitations. If you think the two clients should be on their own pages, I recommend you create a UserVoice entry for the engineering team to review, and others to vote on: https://msip.uservoice.com/

**Comment by bholzmmc** [comment]
While I appreciate the recommendation, I think this is really an item for Microsoft to handle internally.  I don't know Microsoft's processes - the cost, effort and timeliness of the various methods to reduce customer confusion should be taken into account.  Clearly if you do nothing you continue to have confused [and/or other negative feelings toward Microsoft, AiP, et.al.].  Doing any of the possible remediation's will entail work in the documentation site.  I would recommend doing first whatever is the quickest remediation [thereby reducing customer confusion, etc.] even if it is not the best.
