### ISSUE TITLE
confusing section "Editing the registry for the scanner"

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/Azure-RMSDocs#880]
The phrase is incomplete "If you want the same default protection behavior of the Azure Information Protection client, where all files are automatically protected with native or generic protection: Specify the * wildcard as a registry key, and Default as the value data."
It is missing the name must be 'Encryption' 
so the correct/updated statement should read as follows:
"If you want the same default protection behavior of the Azure Information Protection client, where all files are automatically protected with native or generic protection: Specify the * wildcard as a registry key, Encryption as the string (REG_SZ), and Default as the value data."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9c09ab-9d9a-5329-be18-626ab19725d1
* Version Independent ID: e6110fa2-11ac-500b-79de-95ca948159a9
* Content: [Deploy the Azure Information Protection scanner - AIP](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner#editing-the-registry-for-the-scanner)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@itguysocal Thanks for your feedback!  I'll have a look at this.

**Comment by itguysocal** [comment]
![pfile wildcard registry](https://user-images.githubusercontent.com/43482381/57248546-7316f380-6ff7-11e9-9b68-b2cbb548fcaf.png)

**Comment by cabailey** [comment]
@itguysocal Looking at this in context, the purpose of the bullets was to document anything that was specific (different) from the already published instructions.  The bullet points are introduced as "For instructions, see File API configuration from the developer guidance. In this documentation for developers, generic protection is referred to as "PFile". In addition, specific for the scanner:"

Instructions for setting the Encryption value are already included in those instructions, which is why they weren't included in this bullet point (not new/different). But I can see how including this adds clarity, so I'll update this today.  Thanks for flagging!

**Comment by cabailey** [comment]
@itguysocal itguysocal Since this is addressed now, I'll ask for this issue to be closed. Thanks for your feedback!
#please-close
