### ISSUE TITLE
Custom permissions in Office apps: Word, Excel, and PowerPoint

### ISSUE THREAD

**Issue by bernardlam** [MicrosoftDocs/Azure-RMSDocs#929]
This article mentions that support for "Custom permissions in Office apps: Word, Excel, and PowerPoint" is not being planned for Unified Labeling Client. 

However, the following article mentions that "when the label [which allows user-defined permission] is applied, Users are prompted for custom permissions that are then applied as protection using a cloud-based key"

can you help reconcile the apparent conflict?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a13e85-78dd-d4e0-30d9-4acc40f3e11a
* Version Independent ID: 09429982-159f-81fd-a989-901142dee148
* Content: [The client for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#feedback)
* Content Source: [Azure-RMSDocs/rms-client/use-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/use-client.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by bernardlam** [comment]
even this article mentions (under User-defined permissions -> Unified Labelling Client) that "For Word, Excel, PowerPoint, and File Explorer: Supported with the preview client when you configure the label in the Azure portal"

**Comment by cabailey** [comment]
@bernardlam These two options are tricky to distinguish between if you're not familiar with the original Azure Information Protection client ("classic client").  In both cases, end users can select from a dialog box their own permissions, users, and expiry date for protection = custom permissions. The difference is whether this dialog box is label-initiated or user-initiated.
 
For the first scenario, which is now supported in the preview version of the unified labeling client, the admin configures a label for the protection option in the Azure portal called "Set user-defined permissions" and then the checkbox "In Word, Excel, PowerPoint and File Explorer prompt the user for custom permissions". When the user selects the label, they see a dialog box in which the classification is set and cannot be changed, but they are prompted to select their own choice of permissions, users, and expiry date. The important thing here, is that the admin controls if a user can do this per label and the user cannot change the classification of their selected label, only the protection settings.

For the second scenario, for the classic client, the admin has a policy option called "Make the custom permissions option available to users". When this option is enabled, in Office apps, users see an option called "Custom Permissions" under the Protect button (the equivalent of the Sensitivity button for the unified labeling client). If users select this option, they see a similar dialog where they can select their own permissions, users, and expiry date for protection. But they can also select or change a label. Some customers like this option because it always gives end users the flexibility and control to set their own classification as well as protection. But conversely, many customers do not use this option because they don't want users to always have the ability to override the selected label classification or protection settings. 

For the preview version of the unified labeling client, a label now supports prompting users for custom permissions when they select a label - if this setting is configured by an admin. But there is no "Custom Permissions" option under the Sensitivity button on the ribbon.

**Comment by bernardlam** [comment]
thanks for the explanation. it's very clear now!

**Comment by cabailey** [comment]
#please-close
