### ISSUE TITLE
User experience description for classic AIP client is not accurate

### ISSUE THREAD

**Issue by bernardlam** [MicrosoftDocs/Azure-RMSDocs#933]
for users who gets the classic AIP client, the article says "For these users, they have additional features and functionality, but a slightly different experience if they also have devices that run MacOS, iOS, and Android, and these devices have a version of Office that supports sensitivity labels." 

According to a related article (https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels) the labels will not work on MacOS/iOS/Android at all.

Also, the following sentence starts with "for example", but it goes on to describe the UX for these users on Windows but not MacOS/iOS/Android:
"For example, they see a Protect button rather than a Sensitivity button on the Office ribbon, and the Information Protection bar can be displayed by default."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a13e85-78dd-d4e0-30d9-4acc40f3e11a
* Version Independent ID: 09429982-159f-81fd-a989-901142dee148
* Content: [The client for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client)
* Content Source: [Azure-RMSDocs/rms-client/use-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/use-client.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@bernardlam I don't see a discrepancy in the documentation. If you install the classic client rather than the unified labeling client, the user experience is slightly different for using labels in comparison with the other platforms.  So as an admin, you might need to provide your users with two sets of instructions.  That's the point behind the documentation you're quoting (additional functionality vs. consistency for users). For more information about the labeling user experience on Office for Mac, iOS, and Android, see the Office documentation: https://support.office.com/en-us/article/Apply-sensitivity-labels-to-your-documents-and-email-within-Office-2f96e7cd-d5a4-403b-8bd7-4cc636bae0f9 

When you are using labels from the unified labeling store, they can be published from both the Azure portal and from the Office 365 Security & Compliance Center (or Microsoft 365 security center or Microsoft 365 compliance center).  You are using the unified labeling store if you migrated labels in the Azure portal, or you have recently got a subscription for Azure Information Protection (in this case, the Activate button for label migration is not available in the Azure portal). Because not all label settings that you can configure in the Azure portal are supported for unified labels, these are documented as exceptions - and these can be another inconsistency for users.

**Comment by bernardlam** [comment]
@cabailey you wrote: "If you install the classic client rather than the unified labeling client, the user experience is slightly different for using labels in comparison with the other platforms" 

in the scenario described in the article, there is a small subset of users who will get classic AIP client because they need advanced features such as HYOK or user-defined permisssions. For these users they can apply labels with these advanced features in Office on Windows. However, even if these labels are also published to SCC, they won't work properly for Office on MacOS/iOS/Android (as per https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels)

I understand the second paragraph in your response but I think that's besides the point. 

My key point is that the following paragraph in the current article should mention that for the subset of users who needs classic AIP client due to HYOK or user-defined permissions, the same labels that work in Office on Windows won't work in Office for MacOS/iOS/Android.

"For these users, they have additional features and functionality, but a slightly different experience if they also have devices that run MacOS, iOS, and Android, and these devices have a version of Office that supports sensitivity labels. For example, they see a Protect button rather than a Sensitivity button on the Office ribbon, and the Information Protection bar can be displayed by default."

**Comment by cabailey** [comment]
The statement "the same labels that work in Office on Windows [for the classic client] won't work in Office for MacOS/iOS/Android" isn't necessarily true, and isn't true for the majority of label configurations.  If your labels use the unified labeling store, they can be used by the classic client and unified labeling clients, with a few exceptions noted in the label migration instructions.

**Comment by bernardlam** [comment]
" If your labels use the unified labeling store, they can be used by the classic client and unified labeling clients, with a few exceptions noted in the label migration instructions." 

Technically that's true However, in the scenario described in the article does fall into those exception cases. the article mentions that "you deploy the classic client because these users require labels that apply hold your own key (HYOK) protection or prompt for user-defined permissions."

**Comment by cabailey** [comment]
Yes, for these specific labels, you add them to a policy in the Azure portal (for the additional functionality) but not add them to a policy in the Security & Compliance Center (or Microsoft 365 security center, Microsoft compliance center).

**Comment by bernardlam** [comment]
Right, if these labels are not published through SCC, they won't be available on Office on Mac/iOS/Android. and if these labels are published through SCC, they'll be available on Office on Mac/iOS/Android, BUT they won't work properly. 

The scenario described the article is precisely about these advanced labels which has HYOK or user-defined permissions. so that's why I think the following statement is not accurate "For these users, they have additional features and functionality, but a slightly different experience if they also have devices that run MacOS, iOS, and Android, and these devices have a version of Office that supports sensitivity labels."

**Comment by cabailey** [comment]
I'm still not seeing the discrepancy in that sentence:  "For these users, they have additional features and functionality [includes the ability to apply HYOK protection and be prompted for user-defined permissions] but a slightly different experience [can include they don't see labels configured for HYOK and user-defined permissions] if they also have devices that run MacOS, iOS, and Android, and these devices have a version of Office that supports sensitivity labels." 

We can't say they definitely won't see these labels, because admins can publish them although we advise that they don't with a clear description of the outcome.  If admins do publish labels in SCC that are configured for HYOK and user-defined permissions against our guidance, the "different experience" is still true because the labels don't behave the same as they do on the classic client.

**Comment by bernardlam** [comment]
so I think we're agreeing on the actual behaviours, and it comes down to how we describe and characterize the difference in experience.  I'd suggest instead of saying they get a "slightly different experience", we spell out the differences explicitly (similar to how they are described in this thread), as opposed to relying on the reader to connect the dots.

Another point is that it's true when describing these features generically, we can't say these users definitely won't see these labels. However, in this portion of the article, we're talking about a specific scenario. so I thought it would be a good place to explain the nuances and considerations in this particular situation (e.g. explain what a typical admin might choose to do considering all the trade-offs)

**Comment by cabailey** [comment]
At the point this sentence appears in this article, it's still high-level guidance and describes an example deployment strategy of why you might deploy both clients on your network.  It's not the place to explictly list all the differences that users might experience or all the configuration choices for admins, which is why it had a couple of examples that an admin couldn't change and users were most likely to notice.  Two of those examples no longer apply with the latest release, so they are now removed and I've added the sentence "For other differences, see the tables that follow." 

Since there's now a reference for where to find more details on the differences, I'll ask for this thread to be closed.
#please-close
